---
title: 'Generate patient score weighting table'
author: "Robert Allaway (Sage Bionetworks)"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    df_print: paged
    code_fold: hide
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---


```{r echo=TRUE, message=FALSE, warning=FALSE}
set.seed(98109)

library(tidyverse)
library(reticulate)
library(ggplot2)

# Synapse setup to use `reticulate`
use_condaenv("ra2dream")
synapseclient <- reticulate::import('synapseclient')
syn <- synapseclient$Synapse()

# 
calculate_weight <- function(x){
  weight <- dplyr::if_else(x == 0, 1,
            dplyr::if_else(x == 1, 2,
            dplyr::if_else(x>=2 & x<=3, 2.143547,
            dplyr::if_else(x>=4 & x<=7, 3.863745,
            dplyr::if_else(x>=8 & x<=20, 8,
            dplyr::if_else(x>=21 & x<=55, 16,
            dplyr::if_else(x>=56 & x<=148, 32,
            dplyr::if_else(x>=148, 64, 0))))))))
  return(weight)
}

```

```{r include=FALSE}
#login
syn$login()

```


```{r echo=TRUE, message=FALSE, warning=FALSE}
weights <- syn$get("syn22296988")$path %>% read_csv() %>% 
  gather('measurement', 'Overall_SvH', -Patient_ID) %>% 
  filter(measurement == "Overall_Tol") %>% 
  select(-measurement) %>% 
  mutate(weight = calculate_weight(Overall_SvH))

write_csv(weights, "supplemental_table_patient_weights.csv")
```


